[2022-02-06 22:01:38,691] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testes_airflow_docker.get_data scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-02-06 22:01:38,702] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testes_airflow_docker.get_data scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2022-02-06 22:01:38,702] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 22:01:38,702] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-06 22:01:38,702] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 22:01:38,712] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-01-25 00:00:00+00:00
[2022-02-06 22:01:38,718] {standard_task_runner.py:52} INFO - Started process 241 to run task
[2022-02-06 22:01:38,721] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'testes_***_docker', 'get_data', 'scheduled__2022-01-25T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl_crawler_drive.py', '--cfg-path', '/tmp/tmpirfqqh2_', '--error-file', '/tmp/tmpcv4e8d8p']
[2022-02-06 22:01:38,722] {standard_task_runner.py:77} INFO - Job 56: Subtask get_data
[2022-02-06 22:01:38,771] {logging_mixin.py:109} INFO - Running <TaskInstance: testes_***_docker.get_data scheduled__2022-01-25T00:00:00+00:00 [running]> on host 1019d2701f28
[2022-02-06 22:01:38,822] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=testes_***_docker
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-25T00:00:00+00:00
[2022-02-06 22:01:38,823] {python.py:175} INFO - Done. Returned value was: None
[2022-02-06 22:01:38,834] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=testes_***_docker, task_id=get_data, execution_date=20220125T000000, start_date=20220206T220138, end_date=20220206T220138
[2022-02-06 22:01:38,893] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-06 22:01:38,917] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
