[2022-02-06 21:51:17,034] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testes_airflow_docker.get_data scheduled__2022-01-23T00:00:00+00:00 [queued]>
[2022-02-06 21:51:17,042] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: testes_airflow_docker.get_data scheduled__2022-01-23T00:00:00+00:00 [queued]>
[2022-02-06 21:51:17,042] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 21:51:17,042] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-06 21:51:17,043] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-06 21:51:17,054] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_data> on 2022-01-23 00:00:00+00:00
[2022-02-06 21:51:17,058] {standard_task_runner.py:52} INFO - Started process 202 to run task
[2022-02-06 21:51:17,060] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'testes_***_docker', 'get_data', 'scheduled__2022-01-23T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/etl_crawler_drive.py', '--cfg-path', '/tmp/tmpxkjbmf4m', '--error-file', '/tmp/tmp5izgn22z']
[2022-02-06 21:51:17,061] {standard_task_runner.py:77} INFO - Job 52: Subtask get_data
[2022-02-06 21:51:17,100] {logging_mixin.py:109} INFO - Running <TaskInstance: testes_***_docker.get_data scheduled__2022-01-23T00:00:00+00:00 [running]> on host aad8b8df0764
[2022-02-06 21:51:17,140] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=testes_***_docker
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-23T00:00:00+00:00
[2022-02-06 21:51:17,141] {python.py:175} INFO - Done. Returned value was: None
[2022-02-06 21:51:17,150] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=testes_***_docker, task_id=get_data, execution_date=20220123T000000, start_date=20220206T215117, end_date=20220206T215117
[2022-02-06 21:51:17,191] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-06 21:51:17,214] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
